name: inception

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dkolarov/data/mariadb

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dkolarov/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
